# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_UI', '0003_auto_20170209_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email adres'),
        ),
    ]
