# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_UI', '0004_auto_20170210_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='static/img/avatar/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='third_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
