# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_UI', '0008_auto_20170221_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_UI.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_UI.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_UI.Teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='complid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(blank=True),
        ),
    ]
