# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_UI', '0012_group_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(to='admin_UI.Group'),
        ),
    ]
